version: '3'
services:
  app:
    build: ./
    container_name: portfolio_continuos_integration
    image: portfolio_continuos_integration
    ports:
      - "80:80"
    volumes:
      - ./src
    # ports:
    # # ssh
    # - "2222:22"
    # # browser sync
    # - "3000:3000"
    # # external browser sync
    # - "3001:3001"