version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.6-apache-node-browsers
    steps:
      - checkout
      # - run: <command>
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              ./bin/staging-deploy.sh
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./bin/master-deploy.sh
            fi

  # test:
  #   docker:
  #     - image: circleci/<language>:<version TAG>
  #   steps:
  #     - checkout
  #     - run: <command>
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test